services:
  backend:
    build:
      context: ./backend
    container_name: newsbias-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./streamlit_app
    container_name: newsbias-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
