

services:
  backend:
    build:
      context: ./backend
    container_name: newsbias-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - TRANSFORMERS_CACHE=/app/.cache

  frontend:
    build:
      context: ./streamlit_app
    container_name: newsbias-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
    depends_on:
      - backend
